kynan/nbstripout

CHANGES.txt
LICENSE.txt
README.rst
nbstripout.py
setup.py

This is the version I uploaded to PyPI: [nbstripout==0.2.0](https://pypi.python.org/pypi/nbstripout/0.2.0).  I will only modify the `0.2.x` revisions and am happy to assign you as an owner or maintainer if you would like so you can upload changes.  I needed a few additions to get things working with my mercurial workflow:
- Processes multiple files.
- Ignores all files but .ipynb files by default.
- Added -f flag to force stripping other files.
- This is the start of the 0.2.x branch which is maintained for now
in a separate fork.
This does change the default behaviour (which would process any file, but could throw errors if the file was not a notebook) so I have gone with a new minor revision number.

REL,API: 0.2.0 Start branch 0.2.0. Only process .ipynb files unless option -f is used

---

.gitignore
nbstripout.py

The cmd-line interface was working with Python3, but it was not running when nbstripout is installed and used with git gut under Linux (Ubuntu 14.04)

add Python 3 support

---

CHANGES.txt
README.rst
nbstripout.py
tests/test-metadata.t
tests/test-unicode.t
tests/test_metadata.ipynb

This PR provides a simple resolution to issue #17 of providing a mechanism for keep some cells output.  The approach is simply to leave alone cells with either of the following metadata:
**`"keep_output": true`**: This is a custom piece of metadata that can be used to resolve the issue.
In addition, we also respect the following:
**`"init_cell": true`**: This is used by the [`init_cell` nbextension](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/init_cell) to mark cells as initialization cells.  These cells are executed when the notebook is loaded.
1.  The primary use case is a cell that loads CSS styling for a notebook, especially with MathJaX macro definitions. The output from this cell can be imperative for proper rendering of …

ENH: Resolves issue #17 providing a way to keep output in selected cells.

---

nbstripout.py

This PR sets the "collapsed" and "scrolled" cell metadata attributes to false if they exist. This normalizes the cell output style, so that these changes which are easily introduced do not pollute version control.

Normalise cell output style

---

README.rst

This is just a documentation change, I don't think I need to bump the version here.

Simply add 'pip install' instructions to README

---

nbstripout.py
tests/test-diff.t
tests/test-git.t
tests/test_diff.ipynb
tests/test_diff_different.ipynb
tests/test_diff_output.ipynb

This patch ensures that git diff makes a diff of the files after applying nbstripout.
I have also created a test, but I'm not sure about a couple things as I have never used travis, so I have included it here in hopes that someone can help me make it work.
I modified `test-git.t` as follows.
```
$ git init foobar
Initialized empty Git repository in .* (re)
$ cd foobar
$ echo -n "*.txt text" >> .git/info/attributes
$ nbstripout --is-installed
[1]
$ nbstripout --install
$ nbstripout --is-installed
$ git diff --no-ext-diff --unified=0 --exit-code -a --no-prefix ${TESTDIR}/test_diff.ipynb ${TESTDIR}/test_diff_output.ipynb 
$ git diff ${TESTDIR}/test_diff.ipynb ${TESTDIR}/test_diff_different.ipynb 
diff --git a/home/utsekaj42/sandbox/nbstripout/tests/test_diff.ipynb …
```

added support for git diff

---

nbstripout.py
tests/test-keep-count.t
tests/test-keep-output-keep-count.t
tests/test-keep-output.t
tests/test-metadata.t

I developed this for my own use case where I wanted to version control the source and its outputs, but not the execution count and other miscellaneous metadata. These two options give fine grained control of nbstripout's behaviour.

Add options to keep output and/or execution counts

---

README.rst

The current shell pipeline example in readme.rst doesn't use `cat`
while the example in the nbstripout.py
[docstring](https://github.com/kynan/nbstripout/blob/master/nbstripout.py#L29) does.

Change shell pipeline example

---

nbstripout.py

Catch WindowsError exception when git not on path

---

.travis.yml
nbstripout.py
setup.py

I've been using `nbstripout` for a while. For the purpose of this discussion, let's say I have it installed on two machines:
- Server: Ubuntu 14.04, Python 2.7.6
- Desktop: Ubuntu 16.04, Python 3.5.2
I'm on `nbstripout` 0.3.1 and `git` is throwing a lot of weird diffs when I push/pull across the two machines, so I started poking around.
On the desktop, I found that I get empty output from `nbstripout -t`. I investigated and found that the output stream was not flushed properly, so I fixed that. (9c24cbd)
Now, I get output from `nbstripout -t`, but the output between two machines are different. Took me a while to found that `pip3` says I don't even have `nbformat`. I installed `nbformat` and things are working properly now. (852bf85)
So here I am, submitting a pull request.

Fix unexpected behaviors

---

tests/test-git.t

With --no-index, git diff compares two files. Otherwise, it would compare the working directory states of those files to their states in the index.
This should fix #74.
Anyway, please check that this makes sense. I'm not 100% certain I did the right thing.

Fix git diff tests by using --no-index. Fix #74

---

nbstripout.py

Use the same path as for filter.nbstripout.clean but append the '-t' Argument. Relevant if Python is not installed system-wide, e.g. with a distribution package on Windows.

absolute install path for diff.ipynb.textconv, fixes #68

---

nbstripout.py

sys.stdin is None on Windows sometimes, make sure it is well defined, please see issue #80 
better fix, replaces pull request #81

make sure sys.stdin is not None (2), fixes #80

---

nbstripout/_nbstripout.py

Git quotes `"` to `\"`, which is invalid. But it seems to not quote `'` to `\'`, so switch to that.
Also fix the name of 'nbstripout', since it's never going to change.

Fix #111: Properly quote script paths for Git

---

nbstripout/__init__.py
nbstripout/_utils.py
tests/test_keep_output_tags.ipynb
tests/test_keep_output_tags.py
tests/test_keep_output_tags_exception.ipynb

I suggested in #117 that it would be nice to be able to mark a cell for keeping output via the cell tags. Cell tags are easier to see and modify (if you set View > cell toolbar > tags). 
I have implemented this functionality in this pull request. I include tests as well, though I do so with pure `pytest` instead of `cram`, because `cram` does not work on Windows and that's what I have at the moment. In the test fixtures (notebooks), 
`"keep_output": true` as a top-level cell key still works, but I raise an exception if it has both `"keep_output": false` _**and**_ a `keep_output` tag, as that would be an explicit contradiction that the user should resolve. 
**Testing note:** In my test fixtures I denote code cells as supposed to have (or not have) output using a comment line at the …

Support specifying keep_output as a cell tag

---

nbstripout/_nbstripout.py

To solve the issue #110.
I faced the same problem on my Windows environment.
nbstripout converts my ipynb file newline from LF to CRLF when I committing.
About the newline parameter of  ```open``` method and ```TextIOWrapper``` method
>When writing output to the stream, if newline is None, any '\n' characters written are translated to the system default line separator, os.linesep.
https://docs.python.org/3/library/io.html#io.TextIOWrapper
https://docs.python.org/3/library/functions.html#open-newline-parameter
os.linesep is
>The string used to separate (or, rather, terminate) lines on the current platform. This may be a single character, such as '\n' for POSIX, or multiple characters, for example, '\r\n' for Windows.
https://docs.python.org/3/library/os.html#os.linesep
Add ```newline=''``` …

add newline param to open and TextIOWrapper method

---

setup.py

The `nbstripout==0.3.8` package was not built & released correctly, which means that `pip install -U nbstripout` will incorrectly install an incompatible version on `python2` (e.g. https://github.com/SyneRBI/SyneRBI_VM/issues/169)
This PR fixes this issue in future.

fix attempting to install on python2

---

README.rst

There is already
```
types: [jupyter]
```
in `.pre-commit-hooks.yaml`

DOC no need to specify files in pre-commit example

---

nbstripout/_utils.py

The current version of `nbstripout` does not support metadata changes if you use popular adds on: collapsable heading from [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html). 
When using collapsable heading extension when a section is closed or open information is saved in Jupyter Notebook. 
We want to limit all the changes to notebook to useful changes, so information, whether the user is using the extension, is irrelevant. 
As this extension is essentially adding two new fields to the metadata field (either "hidden":True or none and "heading_collapsed:True" or again None) it is only needed to add this fields to ingore line. 
**Sidenote:** Current version from master of repository is not working so for my own …

Adding support for Collapsable headings

---

nbstripout/_utils.py
tests/test-metadata-period.t
tests/test_metadata_period.ipynb

Fixes #143 by checking to see if the `key` passed to `pop_recursive` literally exists in `d`, prior to decomposing the key into nested levels. If it exists, it is stripped. If it doesn't, periods in the key will be interpreted as nesting level delimiters.

Strip metadata with periods in key name

---

README.rst
nbstripout/_nbstripout.py
tests/test-git.t
tests/test-status.t

This PR adds a `--system` argument for system-wide installation.
Since there doesn't seem to be a simple way to figure out the `$(prefix)` variable of the Git installation, I had to resort to a kind of hacky way to figure that one out in order to put the system-wide `gitattributes` file in the correct place (see the `_get_system_gitconfig_folder()` function).
I also fixed the path of the gitattributes file in the documentation when using the `--global` argument, which was incorrectly documented as being `.git/info/attributes` instead of `~/.config/git/attributes`.
I also took the liberty of adding a few newlines to improve readability.

Add a --system argument for system-wide installation

---

README.rst
nbstripout/_nbstripout.py
nbstripout/_utils.py
tests/test-max-size.t
tests/test_max_size.ipynb

I need to be able to strip embedded images and videos from a notebook while leaving the smaller text output (similar to #58). This PR adds a `--max-size` option which removes output larger than `max-size` bytes.
```sh
$ nbstripout --max-size 5K test1.ipynb
$ nbstripout --max-size 100 test2.ipynb
$ nbstripout --max-size 1M test3.ipynb
```
This easily delineates larger binary outputs from smaller textual ones.
I did not want to just filter on keys (an alternative) because a matplotlib animation video may be embedded in a `text/html` key, but I don't want to remove every `text/html` key. I'm also not sure if embedded images are always `image/png` in all kernels and plotting backends.
I've run some ad-hoc benchmarks and computing the size of the outputs in negligible to the overall run time …

Support only stripping outputs larger than a given size

---

README.rst
nbstripout/_nbstripout.py
nbstripout/_utils.py
tests/test-strip-init-cells.t
tests/test_strip_init_cells.ipynb

As mentioned in #156 :
This PR adds a flag: `--strip-init-cells` which alters the current behavior to also remove outputs from init cells.
Reason:
I have a whole bunch of notebooks which have the `init_cell: true` metadata. This generates a nice default set of UI widgets as soon as the notebook is loaded. However, since this is generated automatically, I don't want all the widget output checked into my source repo. Right now, every time a user commits a change to the notebook, we have huge amounts of cell output from the init_cell cells.

Add support for stripping init cells

---

README.rst
nbstripout/_nbstripout.py
nbstripout/_utils.py
tests/test-drop-tagged-cells.t
tests/test_drop_tagged_cells.ipynb

Hi, 
the present pull request adds an apparatus to skip entire cells based on a list of tags that can be passed as command line argument.
It might be unappropriate to suggest such a feature to a tool, that indicates in its name that it strips output only. Having said that, there is already an option that strips empty cells entirely. Therefore I leave the decision up to you :)
My use case is, that I create lots of exercise notebooks for students. Clearing the solution is manual and error-prone labor. With this patch applied a simple makefile can convert solutions to exercises and (unrelated to this tool) convert solutions to a pdf.
Tests pass an I added an additional one.

Add an --drop-tagged-cells="some tags" Option

---

.github/workflows/tests.yml

Split-out PR following https://github.com/kynan/nbstripout/pull/169#discussion_r985213823.

Bump CI actions/checkout to v3 and actions/setup-python to v4

---

pre-commit

Use `$(...)` notation instead of legacy backticks `...`.
Split-out PR following https://github.com/kynan/nbstripout/pull/169#discussion_r985213752.

Fix shellcheck SC2006 in `pre-commit` script

---

README.rst
nbstripout/_nbstripout.py
nbstripout/_utils.py
tests/e2e_notebooks/test_keep_metadata_keys.ipynb
tests/e2e_notebooks/test_keep_metadata_keys.ipynb.expected
tests/test_diff.ipynb
tests/test_end_to_end.py
tests/test_git_integration.py

with `nbstripout --keep-metadata-keys` or git config key `filter.nbstripout.keepmetadatakeys`.
closes #78

feat: add option to keep output style

---

README.rst
nbstripout/_nbstripout.py
tests/test_git_integration.py

Useful to specify e.g. `nbstripout --install --python python3` so not the full path to Python but a more cross-native/container value is put into the git config.
closes #181

Add --python option to --install (#181)

---

README.md

Did the minimal changes to the lint-history example on git-filter-repo to allow using nbstripout while keeping performance by never spawning a second interpreter.
See https://github.com/kynan/nbstripout/issues/193
Tested with 2GB repo, went down to 50MB.

Update README.md with git-filter-repo

---

README.md
nbstripout/_nbstripout.py
tests/test_end_to_end.py

Discussed here #153
The idea is to have a cli flag that works as --dry-run BUT returns a status 1 if any change would have been made on the files.
This PR is still a work in progress, right now its compatible with the behavior of the rest of the flags but I think we need to add a test case that verifies its behavior directly (2 files, one that gets changed, one that doesnt and make sure they exit with the correct error) an additional test I can think of is that no file should return status 1 if it has already been stripped (so .... step 1, verify it returns status 1, make sure no changes are made; step 2 run bstripout, step 3 verify that it returns status 0 on the modified file).

Adds --verify
